# This workflow will build a Java project with Gradle
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v1 # https://github.com/marketplace/actions/gradle-build-action
        with:
          arguments: build
      - name: Create build artifacts
        uses: actions/upload-artifact@v2.2.4 # https://github.com/marketplace/actions/upload-a-build-artifact
        if: always()
        with:
          name: reports-${{ matrix.os }}
          path: |
            lib/build/*.html
            lib/build/reports/
            plugin-gradle/build/reports/
            plugin-gradle/demo/build/reports/decycle/
            plugin-maven/build/reports/
